In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt
from de import initialize_generation, mutation

In [2]:
X = initialize_generation(2, [(0, 100), (-100, 0)])
X

[INFO]: initialized first generation with 20 unique base vectors of dimension 2


[array([ 77.08662299, -64.85898992]),
 array([ 69.96655933, -28.99998089]),
 array([ 57.08740193, -54.17688769]),
 array([ 74.4121902 , -26.33685333]),
 array([ 50.49412935, -38.39537208]),
 array([ 77.80948989, -85.05214304]),
 array([ 34.33141403, -74.13228997]),
 array([ 10.77791761, -66.58009408]),
 array([ 65.19776661, -74.69078493]),
 array([ 52.78634605, -97.48722495]),
 array([ 23.18331617, -29.96826831]),
 array([ 94.48386551, -19.27121136]),
 array([  8.65542911, -21.01595207]),
 array([ 97.46535687, -87.90890452]),
 array([ 14.19840212, -28.16073379]),
 array([ 10.76589923, -47.01815164]),
 array([ 48.00180815, -25.16550289]),
 array([ 81.58633923, -56.50768778]),
 array([ 89.43976997, -21.04108947]),
 array([ 73.61403197, -99.83942288])]

In [7]:
V = mutation(X, 0.8)
len(np.unique(V, axis=0))

20